name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


permissions: write-all

jobs:
  build:   
    runs-on: ubuntu-latest
    steps:
      - name: Run script
        run:  |
          curl --request POST \
          --url https://api.github.com/repos/ee-7-tytylol/solid-bassoon/actions/runs/4967466184/deployment_protection_rule \
          --header 'authorization:Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type:application/json' \
          --data '{"environment_name":"production","state":"approved"}'
